### ISSUE TITLE
Updating a document.

### ISSUE THREAD

**Issue by fabulousduck** [musyoka-morris/pymongoext#1]
As it is not stated anywhere in the documentation to my knowledge. Is there any way to update a document using pymongoext ? calling `.update_one()` on an instance of a model does not work.

**Comment by musyoka-morris** [comment]
Call `update_one` on the model class (Not instance). For example, to update a user document `User.update_one(filter, update)`

Kindly note that the method signature is identical to the `db.collection.update_one` signature in pymongo https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.update_one
